// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZPb46qEduI4Kix8XlQ99g9wmUxBk_Wb8',
    appId: '1:721004085011:web:59cc956835134bfece64e6',
    messagingSenderId: '721004085011',
    projectId: 'technovation2026-4831b',
    authDomain: 'technovation2026-4831b.firebaseapp.com',
    databaseURL: 'https://technovation2026-4831b-default-rtdb.firebaseio.com',
    storageBucket: 'technovation2026-4831b.firebasestorage.app',
    measurementId: 'G-R2Z14E02VQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyPxy7xH5Wwonr_d5kcKgak7UlHE1BL3I',
    appId: '1:721004085011:android:5db308963ce1338dce64e6',
    messagingSenderId: '721004085011',
    projectId: 'technovation2026-4831b',
    databaseURL: 'https://technovation2026-4831b-default-rtdb.firebaseio.com',
    storageBucket: 'technovation2026-4831b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYB7h2Rszv9P5JcFdqg_1Qvni1fEsDnts',
    appId: '1:721004085011:ios:f99791a9c005a417ce64e6',
    messagingSenderId: '721004085011',
    projectId: 'technovation2026-4831b',
    databaseURL: 'https://technovation2026-4831b-default-rtdb.firebaseio.com',
    storageBucket: 'technovation2026-4831b.firebasestorage.app',
    iosBundleId: 'com.example.geminiRecipeGeneration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYB7h2Rszv9P5JcFdqg_1Qvni1fEsDnts',
    appId: '1:721004085011:ios:f99791a9c005a417ce64e6',
    messagingSenderId: '721004085011',
    projectId: 'technovation2026-4831b',
    databaseURL: 'https://technovation2026-4831b-default-rtdb.firebaseio.com',
    storageBucket: 'technovation2026-4831b.firebasestorage.app',
    iosBundleId: 'com.example.geminiRecipeGeneration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZPb46qEduI4Kix8XlQ99g9wmUxBk_Wb8',
    appId: '1:721004085011:web:02e2d8ec1631735cce64e6',
    messagingSenderId: '721004085011',
    projectId: 'technovation2026-4831b',
    authDomain: 'technovation2026-4831b.firebaseapp.com',
    databaseURL: 'https://technovation2026-4831b-default-rtdb.firebaseio.com',
    storageBucket: 'technovation2026-4831b.firebasestorage.app',
    measurementId: 'G-TXEZ85NK9F',
  );

}